#!/usr/bin/sh
#
# unify_locales:
#

# Generate translated desktop files  from desktop.in files
msgfmt \
  --desktop \
  --template=data/applications/bodhi-update-manager.in \
  --keyword=Name \
  --keyword=GenericName \
  --keyword=Comment \
  --keyword=Keywords \
  -d po \
  -o data/applications/bodhi-update-manager.desktop
msgfmt \
  --desktop \
  --template="data/applications/bodhi-update-manager-tray.in" \
  --keyword=Name \
  --keyword=GenericName \
  --keyword=Comment \
  --keyword=Keywords \
  -d po \
  -o data/applications/bodhi-update-manager-tray.desktop
# Generate translated policykit files from policy.in files
msgfmt \
  --xml \
  --template="data/polkit/org.bodhi.updatemanager.apt.policy.in" \
  -d po \
  -o "data/polkit/org.bodhi.updatemanager.apt.policy"

intltool-merge -x po \
	"data/polkit/org.bodhi.updatemanager.apt.policy.in" \
	"data/polkit/org.bodhi.updatemanager.apt.policy"

msgfmt \
  --xml \
  --template="data/polkit/org.bodhi.updatemanager.snap.policy.in" \
  -d po \
  -o "data/polkit/org.bodhi.updatemanager.snap.policy"

intltool-merge -x po \
	"data/polkit/org.bodhi.updatemanager.snap.policy.in" \
	"data/polkit/org.bodhi.updatemanager.snap.policy"
